name: tf27
  
channels:
  - conda-forge
  
dependencies:
  - python=3.9
    
  - pandas
  - scikit-learn
  - matplotlib 
  - seaborn
  - jupyterlab 
  - ipywidgets
  - imbalanced-learn
  
  - pip

  - pip:
    # add pip-distributed libraries
    - tensorflow

